export type EnglishLevel = 'Beginner' | 'Intermediate' | 'Advanced';

/**
 * Interface for the raw news article data fetched from the backend (Bright Data).
 */
export interface NewsResult {
    title: string;
    snippet: string;
    link: string;
    source: string;
    date: string;
}

// Re-using NewsResult for consistency in App.tsx
export type Article = NewsResult;

/**
 * Interface for a single vocabulary item generated by Gemini.
 */
export interface VocabularyItem {
    word: string;
    definition: string;
    articleExample: string;
}

/**
 * Interface for the grammar focus section generated by Gemini.
 */
export interface GrammarFocus {
    topic: string;
    explanation: string;
}

/**
 * Interface for the final, structured lesson object generated by Gemini.
 */
export interface Lesson {
    articleTitle: string;
    vocabularyList: VocabularyItem[];
    comprehensionQuestions: string[]; // Array of question strings
    grammarFocus: GrammarFocus;
}

// Type for the full lesson response from the backend
export interface LessonResponse {
    success: boolean;
    lesson: Lesson;
    originalArticleUrl: string;
    userId: string;
}