export type EnglishLevel = 'Beginner' | 'Intermediate' | 'Advanced';

/**
 * Interface for the raw news article data fetched from the backend (Bright Data).
 */
export interface NewsResult {
    title: string;
    snippet: string;
    link: string;
    source: string;
    date: string;
    // Add other fields Bright Data returns here if needed
}

/**
 * Interface for a single vocabulary item generated by Gemini.
 */
export interface VocabularyItem {
    word: string;
    definition: string;
    articleExample: string;
}

/**
 * Interface for the grammar focus section generated by Gemini.
 */
export interface GrammarFocus {
    topic: string;
    explanation: string;
}

/**
 * Interface for the final, structured lesson object generated by Gemini.
 */
export interface Lesson {
    articleTitle: string;
    vocabularyList: VocabularyItem[];
    comprehensionQuestions: string[]; // Array of question strings
    grammarFocus: GrammarFocus;
}
